name: Build Android APK

on:
  workflow_dispatch: # Ermöglicht den manuellen Start per Knopfdruck

jobs:
  build:
    runs-with: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x' # Passen Sie dies an, falls das Projekt .NET 7 nutzt

    - name: Install MAUI Workload
      run: dotnet workload install maui

    - name: Restore Dependencies
      run: dotnet restore

    - name: Build and Publish APK
      run: |
        dotnet publish -c Release -f net8.0-android /p:AndroidPackageFormat=apk /p:AndroidUnsignedApk=true

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: android-apk
        path: |
          **/bin/Release/*-android/publish/*.apk
